{% set name = "xeus-robot" %}
{% set version = "0.2.2" %}
{% set sha256 = "20d2135c1026ff6baf4c0834c9b91cc29b9f5368671b2c2e2ab24a308694bf5d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xeus-robot/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py36]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - cppzmq >=4.7.1,<5
    - zeromq
    - xtl >=0.7.0,<0.8
    - python
    - xeus-python >=0.10.2,<0.11
    - pybind11 >=2.2.4,<3.0
    - nlohmann_json >=3.3.0,<4.0
    - pybind11_json >=0.2.2,<0.3
  run:
    - python
    - xeus-python >=0.10.2,<0.11
    - robotframework-interpreter  >=0.6.2,<0.7
    - robotframework-lsp
    - jupyterlab_robotmode

test:
  commands:
    - test -f ${PREFIX}/bin/xpython                                                                      # [unix]
    - test -f ${PREFIX}/share/jupyter/kernels/xpython/kernel.json                                        # [unix]
    - if exist %LIBRARY_BIN%\\xpython.exe (exit 0) else (exit 1)                                         # [win]
    - if exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xpython\\kernel.json (exit 0) else (exit 1)    # [win]
    - test -d ${PREFIX}/include/xeus-python                                                              # [unix]
    - test -f ${PREFIX}/include/xeus-python/xinterpreter.hpp                                             # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-python/xeus-pythonConfig.cmake                                    # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-python/xeus-pythonConfigVersion.cmake                             # [unix]
    - if exist %LIBRARY_INC%\\xeus-python\\xinterpreter.hpp (exit 0) else (exit 1)                       # [win]
    - if exist %LIBRARY_LIB%\\cmake\\xeus-python\\xeus-pythonConfig.cmake (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_LIB%\\cmake\\xeus-python\\xeus-pythonConfigVersion.cmake (exit 0) else (exit 1)  # [win]
    # The kernel spec in installed in the general PREFIX
    - if exist %PREFIX%\\share\\jupyter\\kernels\\xpython\\kernel.json (exit 0) else (exit 1)            # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-robot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter kernel for the Robot Framework based on Xeus
  description: xeus-robot is a Jupyter kernel for the Robot Framework based on the Xeus library, a native implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter-xeus/xeus-robot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
